id: I1FA54D9A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:40:48+00:00'
last_modified: '2022-06-10T09:08:49.341405+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25139
  title: ལྷ་ལྡན་ཇོ་བོ་རིན་པོ་ཆེའི་བྱུང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7064':
      image_group_id: I1GS55161
      title: ''
      total_pages: 49
      order: 1
      base_file: 7064.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
